# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

instagram: &instagram
  api_key: <%= ENV["INSTAGRAM_API_KEY"] %>
  secret_key: <%= ENV["INSTAGRAM_SECRET_KEY"] %>

development:
  secret_key_base: 0b4cfd2cf138009c91eae60dcfeef0f5aaba3b25e5318ffb8e6ecba03096bf4a83c46caa5fdda4d61a0235a34054d4d880db4dedca0808431a4c9580b677e0c4
  instagram: *instagram

test:
  secret_key_base: 58c24a0c5e187b2c0bc7b94cc3d45293fa55c353c48503aff664efa96580739995531afd14dd47e74bf25920f145cd27e2d2fa349bc32232fe410deaacd0a8bd
  instagram: *instagram

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  instagram: *instagram


